  
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actionsg

name: getcookie

on:
  workflow_dispatch:
 
  watch:
    types: started
  repository_dispatch:
    types: getcookie
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: mafeilong888/dadonggua
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
          npm install qrcode-terminal
      - name: '运行getcookie'
        run: |
          node getJDCookie.js
          node getJDCookie.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  fqkkurl: ${{ secrets.fqkkurl }}
                  fqkkhd: ${{ secrets.fqkkhd }}
                  fqkkcount: ${{ secrets.fqkkcount }}
                  fqkkxh: ${{ secrets.fqkkxh }}
                  fqtx: ${{ secrets.fqtx }}
                  SCKEY: ${{ secrets.SCKEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  EFORK: ${{ secrets.EFORK }}
                  
